"""Validation and normalization rules for AI-generated bug reports."""

from __future__ import annotations

import hashlib
import re
from typing import Any

from app.config import get_settings
from app.services.routing_service import COMPONENT_MAP

settings = get_settings()


def _normalize_string(value: Any, default: str = "") -> str:
    if value is None:
        return default
    return str(value).strip()


def _sanitize_likely_cause(value: str) -> str:
    lowered = value.lower()
    if "confirmed" in lowered or "root cause" in lowered:
        return re.sub(r"(?i)\bconfirmed\b", "suspected", value)
    return value


def _has_production_impact(evidence: str) -> bool:
    markers = [
        "production",
        "customer",
        "outage",
        "data loss",
        "revenue",
        "payment failure",
        "sev1",
        "incident",
    ]
    lowered = evidence.lower()
    return any(marker in lowered for marker in markers)


def _dedup_key(title: str, actual_behavior: str) -> str:
    content = f"{title.lower()}::{actual_behavior.lower()}".encode("utf-8")
    return hashlib.sha256(content).hexdigest()


def validate_bug_payload(data: dict[str, Any]) -> dict[str, Any]:
    """Normalize and validate a bug payload generated by Claude."""

    title = _normalize_string(data.get("title"))
    if not title:
        raise ValueError("Claude returned an empty bug title.")

    severity = _normalize_string(data.get("severity"), "medium").lower()
    if severity not in settings.allowed_severities:
        raise ValueError(f"Unsupported severity '{severity}'.")

    component = _normalize_string(data.get("component"), "unknown").lower()
    if component not in settings.allowed_components:
        component = "unknown"

    suggested_team = _normalize_string(data.get("suggested_team"), COMPONENT_MAP.get(component, "qa")).lower()
    if suggested_team not in settings.allowed_teams:
        suggested_team = "qa"

    reproduction_steps = data.get("reproduction_steps")
    if reproduction_steps is None:
        reproduction_steps = []
    if not isinstance(reproduction_steps, list):
        raise ValueError("reproduction_steps must be a list.")
    reproduction_steps = [_normalize_string(step) for step in reproduction_steps if _normalize_string(step)]

    summary = _normalize_string(data.get("summary"), "No summary provided.")
    environment = _normalize_string(data.get("environment"), "Unknown")
    expected_behavior = _normalize_string(data.get("expected_behavior"), "Not provided.")
    actual_behavior = _normalize_string(data.get("actual_behavior"), "Not provided.")
    likely_cause = _sanitize_likely_cause(_normalize_string(data.get("likely_cause"), "Unknown hypothesis."))
    tags = [tag.strip().lower() for tag in data.get("tags", []) if str(tag).strip()]

    try:
        confidence = float(data.get("confidence", 0.0))
    except (TypeError, ValueError):
        confidence = 0.0
    confidence = min(max(confidence, 0.0), 1.0)

    evidence = " ".join([summary, actual_behavior, environment, " ".join(reproduction_steps)])
    if severity == "critical" and not _has_production_impact(evidence):
        severity = "high"

    recommended_status = settings.clickup_default_status
    if confidence >= settings.min_bug_confidence and (component == "unknown" or len(reproduction_steps) < 2):
        recommended_status = settings.clickup_triage_status

    normalized = {
        "title": title,
        "summary": summary,
        "severity": severity,
        "component": component,
        "environment": environment,
        "reproduction_steps": reproduction_steps,
        "expected_behavior": expected_behavior,
        "actual_behavior": actual_behavior,
        "likely_cause": likely_cause,
        "suggested_team": suggested_team,
        "confidence": confidence,
        "tags": tags,
        "recommended_status": recommended_status,
        "dedup_key": _dedup_key(title, actual_behavior),
    }

    return normalized
